import type { CountrySlug } from "./destinations";

/**
 * ─────────────────────────────────────────────────────────────────────────
 * LIVE VACANCIES.
 *
 * Built from roles currently advertised by our partner employers in Athens,
 * Thessaloniki, Chania, Málaga, Alicante and Lisbon (July 2026).
 *
 * House rules for this file:
 *  · Employers and end brands stay anonymous. Describe the sector instead
 *    ("a global streaming platform"), never the client name.
 *  · No salary figures. We only publish what we can stand behind, and the
 *    number is confirmed on the first call. `packageHighlight` carries the
 *    hook instead — it is the one line that shows on the job card.
 *  · Everything in `package` must be something the employer actually offers.
 *    If we cannot verify it, it does not go in.
 * ─────────────────────────────────────────────────────────────────────────
 */

export type Job = {
  slug: string;
  title: string;
  language: string;
  category: string;
  country: CountrySlug;
  countryName: string;
  flag: string;
  city: string;
  photo: string;
  alt: string;
  /** Anonymised description of who you would actually work for. */
  employer: string;
  contract: string;
  model: "On-site" | "Hybrid" | "Remote";
  /** One line, shown on the card. The reason to click. */
  packageHighlight: string;
  start: string;
  featured?: boolean;
  summary: string;
  responsibilities: string[];
  requirements: string[];
  package: string[];
};

/* Package blocks shared across employers, so a change to a real-world
   benefit is made in exactly one place. */

const GREECE_FULL = [
  "Flight to Greece booked and paid for you",
  "Hotel accommodation on arrival, then help through the flat search",
  "All relocation paperwork handled with you: AFM, AMKA, bank account",
  "Full training by certified instructors, paid from day one",
  "14 salaries a year, as standard on a Greek contract",
  "Private healthcare and a long list of partner discounts",
  "Free online Greek lessons once you have landed",
  "Performance bonus and a paid referral scheme",
];

const SPAIN_TRANSCOM = [
  "Relocation support into Málaga or Alicante",
  "Help with your NIE and Spanish social security registration",
  "Paid training before you take your first customer",
  "Permanent Spanish contract",
  "Private health insurance",
  "A Nordic and Dutch-speaking community of several hundred colleagues on site",
];

const SPAIN_ATENDER = [
  "Permanent Spanish contract, indefinido from the start",
  "Help with the legal registration, including your CUE card",
  "Hybrid working from an office by Málaga harbour",
  "Five minutes' walk from the train and bus stations",
  "Monthly team dinners, after-work events and company trips",
  "Room to grow the role rather than sit in a queue",
];

export const jobs: Job[] = [
  /* ── PORTUGAL ─────────────────────────────────────────────────────── */
  {
    slug: "dutch-customer-support-lisbon",
    title: "Dutch-speaking Customer Support Agent",
    language: "Dutch",
    category: "Customer advisor",
    country: "portugal",
    countryName: "Portugal",
    flag: "🇵🇹",
    city: "Lisbon",
    photo: "/photos/user-lisbon-golden.jpg",
    alt: "Lisbon at golden hour, the castle above the rooftops and the Tagus beyond",
    employer: "A globally recognised brand, from its Lisbon hub",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Private room in shared accommodation, bills included",
    start: "Intakes every two weeks",
    featured: true,
    summary:
      "The most complete accommodation package we place on. You are picked up at the airport and moved straight into your own room in a shared flat, with rent, electricity and water covered for the length of your contract. No experience needed.",
    responsibilities: [
      "Support Dutch customers by phone, email and live chat",
      "Resolve enquiries and complaints professionally and first time where you can",
      "Escalate the complex cases to the right department with the detail they need",
      "Represent a world-leading brand with a customer-first approach",
    ],
    requirements: [
      "Native or near-native Dutch",
      "Good command of English for internal communication",
      "Calm under pressure and solution-oriented",
      "Willing to relocate to Lisbon, or already living there",
      "No previous customer service experience required",
    ],
    package: [
      "Full relocation support to Lisbon",
      "Airport pick-up when you land",
      "Private room in shared accommodation for the length of your contract",
      "Rent, electricity and water all included",
      "Fully paid training from day one",
      "Permanent full-time contract",
      "A multicultural team with colleagues from across Europe",
    ],
  },

  /* ── GREECE · Dutch ───────────────────────────────────────────────── */
  {
    slug: "dutch-streaming-support-athens",
    title: "Dutch-speaking Customer Expert, Streaming",
    language: "Dutch",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/athens-golden.jpg",
    alt: "The Acropolis at golden hour above Athens",
    employer: "A global streaming platform",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · 14 salaries a year",
    start: "Intakes monthly",
    summary:
      "Help Dutch subscribers of one of the world's biggest streaming services over chat and phone, from Athens. Being the person in your group who has already seen everything is genuinely an advantage here.",
    responsibilities: [
      "Answer payment and account how-to questions in Dutch",
      "Troubleshoot streaming quality and playback issues",
      "Help subscribers find their way around the platform",
      "Keep the tone human rather than scripted",
    ],
    requirements: [
      "Excellent Dutch",
      "Fluent English",
      "Confident with computers and quick to pick up new tools",
      "Being a heavy streamer is considered an asset",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "dutch-software-support-athens",
    title: "Dutch-speaking Technical Support, Software",
    language: "Dutch",
    category: "Technical support",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/athens-acropolis-city.jpg",
    alt: "The Acropolis above Athens with the sea beyond",
    employer: "A global software company",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · certified training",
    start: "Intakes monthly",
    summary:
      "First-line technical support in Dutch for one of the largest software companies in the world. The training is genuinely good and the certification travels with you.",
    responsibilities: [
      "Diagnose and resolve software and account issues over phone and chat",
      "Walk customers through setup, licensing and configuration",
      "Escalate with clear reproduction steps",
      "Keep the knowledge base honest",
    ],
    requirements: [
      "Excellent Dutch",
      "Fluent English",
      "Genuine interest in technology, prior experience is a plus not a must",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "dutch-home-technology-support-athens",
    title: "Dutch-speaking Customer Expert, Home Technology",
    language: "Dutch",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/greece-taverna-alley.jpg",
    alt: "Bougainvillea over a taverna terrace in a Greek alley",
    employer: "A premium home technology brand",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · free Greek lessons",
    start: "Intakes monthly",
    summary:
      "Support Dutch customers of a design-led home technology brand from Athens. Product-heavy rather than script-heavy, so you actually learn something.",
    responsibilities: [
      "Answer product, warranty and troubleshooting questions in Dutch",
      "Arrange repairs and replacements end to end",
      "Feed recurring product issues back to the brand",
    ],
    requirements: [
      "Excellent Dutch",
      "Fluent English",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "dutch-b2b-sales-athens",
    title: "Dutch-speaking B2B Sales Expert, IT Solutions",
    language: "Dutch",
    category: "Inside sales",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/greece-mykonos.jpg",
    alt: "Whitewashed houses above turquoise water in Mykonos",
    employer: "An enterprise IT solutions provider",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · commission on top",
    start: "Rolling intakes",
    summary:
      "Sell IT solutions into the Dutch business market from Athens. A real commercial role with a career track, not a call list, and the commission is on top of the standard Greek package.",
    responsibilities: [
      "Qualify inbound leads and run first calls in Dutch",
      "Build a pipeline of business accounts",
      "Run product conversations and hand over cleanly",
      "Keep the CRM in a state a colleague could pick up",
    ],
    requirements: [
      "Excellent Dutch",
      "Fluent English",
      "Some sales or commercial experience",
      "EU passport or the right to work in Greece",
    ],
    package: [...GREECE_FULL, "Uncapped commission on top of base"],
  },
  {
    slug: "dutch-ai-trust-safety-athens",
    title: "Dutch-speaking AI Trust and Safety Expert",
    language: "Dutch",
    category: "Content review",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/greece-milos-cove.jpg",
    alt: "Fishing boats in a turquoise cove on Milos",
    employer: "A generative AI programme",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · the newest desk in Athens",
    start: "Intakes monthly",
    summary:
      "Review and rate generative AI output in Dutch against written policy. One of the newest and most interesting desks in Athens, and a genuinely useful line on a CV over the next few years.",
    responsibilities: [
      "Review AI-generated content in Dutch against policy guidelines",
      "Rate output for accuracy, safety and tone",
      "Document edge cases so the guidelines improve",
    ],
    requirements: [
      "Excellent Dutch, including a good ear for register and nuance",
      "Fluent English",
      "Comfortable with detailed written guidelines",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },

  /* ── GREECE · Danish ──────────────────────────────────────────────── */
  {
    slug: "danish-travel-platform-athens",
    title: "Danish-speaking Customer Expert, Travel",
    language: "Danish",
    category: "Travel consultant",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/user-greece-cove.jpg",
    alt: "A turquoise cove with umbrellas on a white pebble beach in Greece",
    employer: "A global travel booking platform",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · 14 salaries a year",
    start: "Intakes monthly",
    featured: true,
    summary:
      "Look after Danish travellers for one of the largest booking platforms in the world, from Athens. Busy, varied, and you will never take the same call twice.",
    responsibilities: [
      "Handle bookings, changes and cancellations in Danish",
      "Work with hotels and partners to sort disrupted trips",
      "Own each case through to a resolution",
    ],
    requirements: [
      "Excellent Danish",
      "Fluent English",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "danish-electronics-support-athens",
    title: "Danish-speaking Customer Expert, Electronics",
    language: "Danish",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/athens-golden.jpg",
    alt: "The Acropolis at golden hour above Athens",
    employer: "A world-leading consumer electronics manufacturer",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · Athens or Thessaloniki",
    start: "Intakes monthly",
    summary:
      "Support Danish customers of a household-name electronics brand. You can take this one in Athens or in Thessaloniki, which is cheaper again and has the better food.",
    responsibilities: [
      "Answer product, warranty and repair questions in Danish",
      "Coordinate with service centres to get devices fixed",
      "Log cases so the next person can pick them up",
    ],
    requirements: [
      "Excellent Danish",
      "Fluent English",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "danish-financial-support-athens",
    title: "Danish-speaking Financial Customer Expert",
    language: "Danish",
    category: "Back office",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/athens-acropolis-city.jpg",
    alt: "The Acropolis above Athens with the sea beyond",
    employer: "A financial services provider",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · structured, process-led work",
    start: "Intakes monthly",
    summary:
      "Financial customer support in Danish from Athens. Structured, detail-driven work that suits people who would rather follow a process properly than improvise.",
    responsibilities: [
      "Support Danish customers with accounts, cards and payments",
      "Run identity and compliance checks to the letter",
      "Keep records that stand up to an audit",
    ],
    requirements: [
      "Excellent Danish",
      "Fluent English",
      "Comfortable with detail and process",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "danish-content-moderator-athens",
    title: "Danish-speaking Social Media Content Moderator",
    language: "Danish",
    category: "Content review",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/greece-taverna-alley.jpg",
    alt: "Bougainvillea over a taverna terrace in a Greek alley",
    employer: "A major social media platform",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · dedicated wellbeing support",
    start: "Intakes monthly",
    summary:
      "Review Danish-language content against platform policy. We will be straight with you: some of the material is difficult. The wellbeing support on this programme is real and it is one of the reasons we place on it.",
    responsibilities: [
      "Review reported content against written policy",
      "Apply guidelines consistently and document the call",
      "Flag policy gaps and edge cases to the policy team",
    ],
    requirements: [
      "Excellent Danish",
      "Fluent English",
      "Resilience, and a willingness to use the support that is provided",
      "EU passport or the right to work in Greece",
    ],
    package: [
      ...GREECE_FULL,
      "Dedicated psychological and wellbeing support throughout",
    ],
  },
  {
    slug: "danish-appliance-support-thessaloniki",
    title: "Danish-speaking Customer Expert, Appliances",
    language: "Danish",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Thessaloniki",
    photo: "/photos/thessaloniki-waterfront.jpg",
    alt: "Thessaloniki's dense waterfront meeting the Thermaic Gulf",
    employer: "A premium German appliance manufacturer",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · northern Greece, lower rents",
    start: "Intakes monthly",
    summary:
      "Thessaloniki is Greece's second city, a student town with the best food in the country and rents below Athens. This desk supports Danish customers of a premium appliance brand.",
    responsibilities: [
      "Answer product, warranty and service questions in Danish",
      "Arrange engineer visits and repairs",
      "Keep the customer informed without being chased",
    ],
    requirements: [
      "Excellent Danish",
      "Fluent English",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },

  /* ── GREECE · Norwegian ───────────────────────────────────────────── */
  {
    slug: "norwegian-payments-support-crete",
    title: "Norwegian-speaking Customer Expert, Payments",
    language: "Norwegian",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Chania, Crete",
    photo: "/photos/crete-chania-harbour.jpg",
    alt: "The Venetian harbour at Chania, Crete, lined with pastel houses",
    employer: "A global payments platform",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · this one is on Crete",
    start: "Intakes monthly",
    featured: true,
    summary:
      "Yes, Crete. A global payments platform runs a support hub in Chania, and this is the Norwegian desk. The Venetian harbour is a fifteen-minute walk from the office and the beaches south of town are close to empty by October.",
    responsibilities: [
      "Support Norwegian customers with payments, accounts and disputes",
      "Investigate transactions and explain the outcome plainly",
      "Handle identity and fraud checks carefully",
    ],
    requirements: [
      "Excellent Norwegian",
      "Fluent English",
      "Comfortable with detail",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "norwegian-delivery-support-athens",
    title: "Norwegian-speaking Customer Expert, Delivery",
    language: "Norwegian",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/athens-golden.jpg",
    alt: "The Acropolis at golden hour above Athens",
    employer: "A large delivery and logistics service",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · 14 salaries a year",
    start: "Intakes monthly",
    summary:
      "Norwegian speakers are scarce on the ground in Athens, which is why these desks are looked after properly. Support customers of a large delivery service by phone, email and chat.",
    responsibilities: [
      "Resolve delivery, tracking and refund issues in Norwegian",
      "Coordinate with couriers and merchants",
      "Own the case until the customer has an answer",
    ],
    requirements: [
      "Excellent Norwegian",
      "Fluent English",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "norwegian-imaging-support-athens",
    title: "Norwegian-speaking Customer Expert, Cameras and Imaging",
    language: "Norwegian",
    category: "Technical support",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/greece-mykonos.jpg",
    alt: "Whitewashed houses above turquoise water in Mykonos",
    employer: "A leading camera and imaging brand",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · a desk for camera people",
    start: "Intakes monthly",
    summary:
      "Technical support in Norwegian for a camera and imaging brand. If you already own too many lenses, this is the desk where that finally pays.",
    responsibilities: [
      "Support customers with camera setup, firmware and accessories",
      "Diagnose faults and arrange service",
      "Explain technical answers in plain Norwegian",
    ],
    requirements: [
      "Excellent Norwegian",
      "Fluent English",
      "Interest in photography or consumer tech",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "norwegian-content-moderator-athens",
    title: "Norwegian-speaking Social Media Content Moderator",
    language: "Norwegian",
    category: "Content review",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/greece-milos-cove.jpg",
    alt: "Fishing boats in a turquoise cove on Milos",
    employer: "A major social media platform",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · dedicated wellbeing support",
    start: "Intakes monthly",
    summary:
      "Review Norwegian-language content against platform policy. Some of the material is difficult, and the wellbeing support on this programme is real rather than a line in a handbook.",
    responsibilities: [
      "Review reported content against written policy",
      "Apply guidelines consistently and document the call",
      "Flag policy gaps to the policy team",
    ],
    requirements: [
      "Excellent Norwegian",
      "Fluent English",
      "Resilience, and a willingness to use the support provided",
      "EU passport or the right to work in Greece",
    ],
    package: [
      ...GREECE_FULL,
      "Dedicated psychological and wellbeing support throughout",
    ],
  },
  {
    slug: "norwegian-appliance-support-thessaloniki",
    title: "Norwegian-speaking Customer Expert, Appliances",
    language: "Norwegian",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Thessaloniki",
    photo: "/photos/thessaloniki-sunset-boats.jpg",
    alt: "Sailing boats on the Thermaic Gulf at sunset off Thessaloniki",
    employer: "A premium German appliance manufacturer",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · northern Greece, lower rents",
    start: "Intakes monthly",
    summary:
      "The Norwegian desk in Thessaloniki. Cheaper than Athens, a long waterfront promenade to walk home along, and Halkidiki's beaches an hour away.",
    responsibilities: [
      "Answer product, warranty and service questions in Norwegian",
      "Arrange engineer visits and repairs",
      "Keep customers informed without being chased",
    ],
    requirements: [
      "Excellent Norwegian",
      "Fluent English",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },

  /* ── GREECE · Greek ───────────────────────────────────────────────── */
  {
    slug: "danish-customer-service-malaga",
    title: "Danish-speaking Customer Service Representative",
    language: "Danish",
    category: "Customer advisor",
    country: "spain",
    countryName: "Spain",
    flag: "🇪🇸",
    city: "Málaga",
    photo: "/photos/user-malaga-aerial.jpg",
    alt: "Málaga from above, the bullring and the port meeting the Mediterranean",
    employer: "A large multilingual service hub on the Costa del Sol",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "300 days of sun · a Nordic community already on site",
    start: "Rolling intakes",
    summary:
      "Málaga has one of the largest concentrations of Nordic and Dutch speakers working in Europe, and several hundred of them are in these two offices. You will not be the only Dane in the building, which matters more in month three than you would think.",
    responsibilities: [
      "Support Danish customers by phone, email and chat",
      "Resolve account, order and service issues end to end",
      "Work to quality and satisfaction targets rather than raw call counts",
    ],
    requirements: [
      "Native or near-native Danish",
      "Good English for internal communication",
      "EU passport or the right to work in Spain",
      "No previous experience required",
    ],
    package: SPAIN_TRANSCOM,
  },
  {
    slug: "norwegian-customer-service-malaga",
    title: "Norwegian-speaking Customer Service Representative",
    language: "Norwegian",
    category: "Customer advisor",
    country: "spain",
    countryName: "Spain",
    flag: "🇪🇸",
    city: "Málaga",
    photo: "/photos/malaga-sunset.jpg",
    alt: "Sunset over the harbour in Málaga",
    employer: "A large multilingual service hub on the Costa del Sol",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "300 days of sun · a Nordic community already on site",
    start: "Rolling intakes",
    summary:
      "The Norwegian desk in Málaga. Same offices, same Nordic community, and a two-and-a-half hour flight home when you need it.",
    responsibilities: [
      "Support Norwegian customers by phone, email and chat",
      "Resolve account, order and service issues end to end",
      "Flag recurring problems back to the client team",
    ],
    requirements: [
      "Native or near-native Norwegian",
      "Good English for internal communication",
      "EU passport or the right to work in Spain",
      "No previous experience required",
    ],
    package: SPAIN_TRANSCOM,
  },
  {
    slug: "dutch-telecom-support-alicante",
    title: "Dutch-speaking Customer Expert, Telecoms",
    language: "Dutch",
    category: "Customer advisor",
    country: "spain",
    countryName: "Spain",
    flag: "🇪🇸",
    city: "Alicante",
    photo: "/photos/user-alicante-explanada.jpg",
    alt: "Palms and the Explanada promenade in Alicante under a Spanish flag",
    employer: "A Dutch telecoms provider, from its Alicante hub",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Costa Blanca · a Dutch brand, a Spanish contract",
    start: "Rolling intakes",
    summary:
      "A Dutch telecoms brand runs its customer desk from Alicante, on the Costa Blanca. You work in Dutch for a company you already know, on a Spanish contract, with the Explanada and the beach ten minutes from the office.",
    responsibilities: [
      "Support Dutch customers with subscriptions, billing and connectivity",
      "Troubleshoot mobile and home internet issues",
      "Handle upgrades and retention conversations",
    ],
    requirements: [
      "Native or near-native Dutch",
      "Good English for internal communication",
      "EU passport or the right to work in Spain",
      "No previous experience required",
    ],
    package: SPAIN_TRANSCOM,
  },
  {
    slug: "dutch-customer-support-malaga",
    title: "Dutch-speaking Customer Support Agent",
    language: "Dutch",
    category: "Customer advisor",
    country: "spain",
    countryName: "Spain",
    flag: "🇪🇸",
    city: "Málaga",
    photo: "/photos/malaga-sunset.jpg",
    alt: "Sunset over the harbour in Málaga",
    employer: "A people-first support company by Málaga harbour",
    contract: "Permanent",
    model: "Hybrid",
    packageHighlight: "Hybrid · indefinido contract from the start",
    start: "Rolling intakes",
    summary:
      "The smallest employer we place with, and for a lot of people the best fit. A support team by Málaga harbour that works for product-led European companies, with hybrid working and a permanent indefinido contract from day one rather than after probation.",
    responsibilities: [
      "Handle incoming enquiries and support tickets in Dutch, thoughtfully and on time",
      "Solve the problem rather than close the ticket",
      "Work with the wider team on how support itself gets better",
    ],
    requirements: [
      "Fluent Dutch",
      "Good English",
      "Quick with digital tools",
      "Living in Málaga or relocating there",
    ],
    package: SPAIN_ATENDER,
  },
  {
    slug: "danish-customer-support-malaga-hybrid",
    title: "Danish-speaking Customer Support Agent",
    language: "Danish",
    category: "Customer advisor",
    country: "spain",
    countryName: "Spain",
    flag: "🇪🇸",
    city: "Málaga",
    photo: "/photos/malaga-beach.jpg",
    alt: "Palm-lined beach promenade in Málaga",
    employer: "A people-first support company by Málaga harbour",
    contract: "Permanent",
    model: "Hybrid",
    packageHighlight: "Hybrid · indefinido contract from the start",
    start: "Rolling intakes",
    summary:
      "A small, deliberately un-corporate support team by Málaga harbour, working for product-led European companies. Hybrid, permanent from day one, and close enough to the water to swim before work.",
    responsibilities: [
      "Handle incoming enquiries and support tickets in Danish",
      "Keep a solution-oriented approach rather than a scripted one",
      "Contribute to how the team improves its own process",
    ],
    requirements: [
      "Fluent Danish",
      "Good English",
      "Quick with digital tools",
      "Living in Málaga or relocating there",
    ],
    package: SPAIN_ATENDER,
  },
  {
    slug: "norwegian-customer-support-malaga-hybrid",
    title: "Norwegian-speaking Customer Support Agent",
    language: "Norwegian",
    category: "Customer advisor",
    country: "spain",
    countryName: "Spain",
    flag: "🇪🇸",
    city: "Málaga",
    photo: "/photos/malaga-beach.jpg",
    alt: "Palm-lined beach promenade in Málaga",
    employer: "A people-first support company by Málaga harbour",
    contract: "Permanent",
    model: "Hybrid",
    packageHighlight: "Hybrid · indefinido contract from the start",
    start: "Rolling intakes",
    summary:
      "The Norwegian seat on a small support team by Málaga harbour. Hybrid working, a permanent contract from the start, and a five-minute walk from the train station.",
    responsibilities: [
      "Handle incoming enquiries and support tickets in Norwegian",
      "Solve the problem properly rather than close the ticket",
      "Help shape how the team works",
    ],
    requirements: [
      "Fluent Norwegian",
      "Good English",
      "Quick with digital tools",
      "Living in Málaga or relocating there",
    ],
    package: SPAIN_ATENDER,
  },
  /* ── GERMAN ───────────────────────────────────────────────────────── */
  {
    slug: "german-customer-care-athens",
    title: "German-speaking Customer Care Expert",
    language: "German",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/athens-golden.jpg",
    alt: "The Acropolis at golden hour above Athens",
    employer: "A global consumer brand, from its Athens hub",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · 14 salaries a year",
    start: "Intakes monthly",
    summary:
      "The biggest and most consistently open desk in Athens. German speakers are hired here year-round, which means intakes are frequent and you rarely wait long for a start date.",
    responsibilities: [
      "Support German customers by phone, email and chat",
      "Resolve account, order and product issues end to end",
      "Escalate cleanly and keep the customer informed",
    ],
    requirements: [
      "Excellent German",
      "Fluent English",
      "EU passport or the right to work in Greece",
      "No previous experience required",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "german-technical-support-athens",
    title: "German-speaking Technical Support, Software",
    language: "German",
    category: "Technical support",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/athens-acropolis-city.jpg",
    alt: "The Acropolis above Athens with the sea beyond",
    employer: "A global software company",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · certified training",
    start: "Intakes monthly",
    summary:
      "First and second-line technical support in German for one of the largest software companies in the world. The training is properly certified and the certification travels with you.",
    responsibilities: [
      "Diagnose and resolve software and account issues over phone and chat",
      "Walk customers through setup, licensing and configuration",
      "Escalate with clear reproduction steps",
    ],
    requirements: [
      "Excellent German",
      "Fluent English",
      "Genuine interest in technology, prior experience a plus not a must",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "german-customer-care-thessaloniki",
    title: "German-speaking Customer Care Expert",
    language: "German",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Thessaloniki",
    photo: "/photos/thessaloniki-waterfront.jpg",
    alt: "Thessaloniki's dense waterfront meeting the Thermaic Gulf",
    employer: "A global consumer brand, from its Thessaloniki hub",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · northern Greece, lower rents",
    start: "Intakes monthly",
    summary:
      "Same package as Athens, noticeably lower rent, and a long waterfront promenade to walk home along. Thessaloniki is a student city with the best food in the country.",
    responsibilities: [
      "Support German customers across phone, email and chat",
      "Own each case through to resolution",
      "Feed recurring problems back to the client team",
    ],
    requirements: [
      "Excellent German",
      "Fluent English",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "german-customer-service-malaga",
    title: "German-speaking Customer Service Representative",
    language: "German",
    category: "Customer advisor",
    country: "spain",
    countryName: "Spain",
    flag: "🇪🇸",
    city: "Málaga",
    photo: "/photos/user-malaga-aerial.jpg",
    alt: "Málaga from above, the bullring and the port meeting the Mediterranean",
    employer: "A large multilingual service hub on the Costa del Sol",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Málaga Valley · a German-speaking community on site",
    start: "Rolling intakes",
    featured: true,
    summary:
      "Málaga is now the fastest-growing tech city in Spain, with Google's largest European cybersecurity centre and Vodafone's research hub both on the seafront. This is the German desk in one of the two big service hubs, and there are already several hundred northern Europeans in the building.",
    responsibilities: [
      "Support German customers by phone, email and chat",
      "Resolve account, order and service issues end to end",
      "Work to quality targets rather than raw call counts",
    ],
    requirements: [
      "Native or near-native German",
      "Good English for internal communication",
      "EU passport or the right to work in Spain",
      "No previous experience required",
    ],
    package: SPAIN_TRANSCOM,
  },
  {
    slug: "german-customer-support-malaga-hybrid",
    title: "German-speaking Customer Support Agent",
    language: "German",
    category: "Customer advisor",
    country: "spain",
    countryName: "Spain",
    flag: "🇪🇸",
    city: "Málaga",
    photo: "/photos/spain-tapas-table.jpg",
    alt: "A table of croquetas, jamón and cold drinks in the Spanish sun",
    employer: "A people-first support company by Málaga harbour",
    contract: "Permanent",
    model: "Hybrid",
    packageHighlight: "Hybrid · indefinido contract from the start",
    start: "Rolling intakes",
    summary:
      "The smallest employer we place with, and for a lot of people the best fit. A support team by Málaga harbour working for product-led European companies, hybrid, with a permanent indefinido contract from day one rather than after probation.",
    responsibilities: [
      "Handle incoming enquiries and support tickets in German",
      "Solve the problem rather than close the ticket",
      "Help shape how the team works",
    ],
    requirements: [
      "Fluent German",
      "Good English",
      "Quick with digital tools",
      "Living in Málaga or relocating there",
    ],
    package: SPAIN_ATENDER,
  },

  /* ── SWEDISH ──────────────────────────────────────────────────────── */
  {
    slug: "swedish-customer-expert-athens",
    title: "Swedish-speaking Customer Expert",
    language: "Swedish",
    category: "Customer advisor",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/greek-taverna-table.jpg",
    alt: "A taverna table with blue chairs set right beside the sea",
    employer: "A global consumer brand, from its Athens hub",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · 14 salaries a year",
    start: "Intakes monthly",
    summary:
      "Swedish speakers are scarce on the ground in Athens, which is why these desks come with the full package and get looked after. Support Swedish customers across phone, email and chat.",
    responsibilities: [
      "Support Swedish customers across all channels",
      "Own each case through to resolution",
      "Work with the Nordic team on tone and translations",
    ],
    requirements: [
      "Excellent Swedish",
      "Fluent English",
      "EU passport or the right to work in Greece",
    ],
    package: GREECE_FULL,
  },
  {
    slug: "swedish-content-moderator-athens",
    title: "Swedish-speaking Social Media Content Moderator",
    language: "Swedish",
    category: "Content review",
    country: "greece",
    countryName: "Greece",
    flag: "🇬🇷",
    city: "Athens",
    photo: "/photos/greece-milos-cove.jpg",
    alt: "Fishing boats in a turquoise cove on Milos",
    employer: "A major social media platform",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "Flight and hotel covered · dedicated wellbeing support",
    start: "Intakes monthly",
    summary:
      "Review Swedish-language content against platform policy. Some of the material is difficult, and the wellbeing support on this programme is real rather than a line in a handbook.",
    responsibilities: [
      "Review reported content against written policy",
      "Apply guidelines consistently and document the call",
      "Flag policy gaps to the policy team",
    ],
    requirements: [
      "Excellent Swedish",
      "Fluent English",
      "Resilience, and a willingness to use the support provided",
      "EU passport or the right to work in Greece",
    ],
    package: [
      ...GREECE_FULL,
      "Dedicated psychological and wellbeing support throughout",
    ],
  },
  {
    slug: "swedish-customer-service-malaga",
    title: "Swedish-speaking Customer Service Representative",
    language: "Swedish",
    category: "Customer advisor",
    country: "spain",
    countryName: "Spain",
    flag: "🇪🇸",
    city: "Málaga",
    photo: "/photos/malaga-sunset.jpg",
    alt: "Sunset over the harbour in Málaga",
    employer: "A large multilingual service hub on the Costa del Sol",
    contract: "Permanent",
    model: "On-site",
    packageHighlight: "300 days of sun · a Nordic community already on site",
    start: "Rolling intakes",
    summary:
      "The Swedish desk in Málaga. Several hundred Swedes, Danes, Norwegians and Dutch already work across these two offices, so the hardest part of moving is largely solved before you arrive.",
    responsibilities: [
      "Support Swedish customers by phone, email and chat",
      "Resolve account, order and service issues end to end",
      "Flag recurring problems back to the client team",
    ],
    requirements: [
      "Native or near-native Swedish",
      "Good English for internal communication",
      "EU passport or the right to work in Spain",
      "No previous experience required",
    ],
    package: SPAIN_TRANSCOM,
  },
];

export const featuredJobs = jobs.filter((j) => j.featured);

export const jobBySlug = (slug: string) => jobs.find((j) => j.slug === slug);

export const jobsByCountry = (country: CountrySlug) =>
  jobs.filter((j) => j.country === country);

export const jobLanguages = [...new Set(jobs.map((j) => j.language))].sort();
export const jobCategories = [...new Set(jobs.map((j) => j.category))].sort();
export const jobCities = [...new Set(jobs.map((j) => j.city))].sort();
